version: '3.5'
services:
  mdgkb_server:
    container_name: mdgkb-server
    build:
      context: .
      dockerfile: Dockerfile
      target: 'dev'
    privileged: true
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: always
    volumes:
      - ./:/go/src/mdgkb-server
    environment:
      - DB_DB=${DB_DB}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - SERVER_PORT=${SERVER_PORT}
    network_mode: "host"

networks:
  default:
    external:
      name: mdgkb-network
